AppBundle\Entity\Contacts:
    type: entity
    table: contacts
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        text:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        addedAt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: added_at
        answeredAt:
            type: datetime
            nullable: true
            column: answered_at
        isViewed:
            type: boolean
            nullable: true
            options:
                default: '0'
            column: is_viewed
        isAnswered:
            type: boolean
            nullable: true
            options:
                default: '0'
            column: is_answered
        isJunk:
            type: boolean
            nullable: true
            options:
                default: '0'
            column: is_junk
    lifecycleCallbacks: {  }
