AppBundle\Entity\OnlinerProfilesBanned:
    type: entity
    table: onliner__profiles_banned
    indexes:
        created_at:
            columns:
                - created_at
    id:
        onlUserId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: onl_user_id
            generator:
                strategy: IDENTITY
    fields:
        onlUsername:
            type: string
            nullable: false
            length: 32
            options:
                fixed: false
            column: onl_username
        createdAt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: created_at
    lifecycleCallbacks: {  }
