AppBundle\Entity\OnlinerModerators:
    type: entity
    table: onliner__moderators
    uniqueConstraints:
        onl_username:
            columns:
                - onl_username
    id:
        onlUserId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: onl_user_id
            generator:
                strategy: IDENTITY
    fields:
        onlUsername:
            type: string
            nullable: false
            length: 32
            options:
                fixed: false
            column: onl_username
        moderatedOnlUserIds:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: moderated_onl_user_ids
        firstActivityAt:
            type: datetime
            nullable: true
            column: first_activity_at
        latestActivityAt:
            type: datetime
            nullable: true
            column: latest_activity_at
        addedAt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: added_at
    lifecycleCallbacks: {  }
