AppBundle\Entity\OnlinerCommentsIdsCensored:
    type: entity
    table: onliner__comments_ids_censored
    indexes:
        created_at:
            columns:
                - created_at
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        createdAt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: created_at
    lifecycleCallbacks: {  }
